### ISSUE TITLE
ReferenceError: REQUEST_APPS is not defined

### ISSUE THREAD

**Issue by bertolo1988** [Rohitkrops/ssr#1]
I did npm run build && npm run start and got:

`ReferenceError: REQUEST_APPS is not defined`

How can i define it?

**Comment by Matt-Lauderdale** [comment]
`import { REQUEST_APPS,  RECEIVE_APPS } from './actions';`

**Comment by RibbtDev** [comment]
Thank you @Matt-Lauderdale for the quick solution. It's now merged. 

@bertolo1988 pull new code.
