### ISSUE TITLE
No CSS and Image in Chrome Network preview

### ISSUE THREAD

**Issue by bnayak0225** [Rohitkrops/ssr#13]
![image](https://user-images.githubusercontent.com/36666122/79095499-2c3d8c00-7d78-11ea-89c4-2e7fadd18186.png)

No Image or Css chrome Network preview tab, All though website is working fine in browser. Expecting a clear a reason from you.

**Comment by RibbtDev** [comment]
Hi @bnayak0225 , I am glad that you shared your concern. 

To understand this you should know what that preview is, page render snapshots, and asset download priorities of browsers. 

To understand it better please take a look into network call waterfall and please go through this resource: [Preload, Prefetch And Priorities in Chrome](https://medium.com/reloading/preload-prefetch-and-priorities-in-chrome-776165961bbf) by Addy Osmani. 

The answer to your question with reference to this project is: 
1. The document was downloaded and the preview was generated. At this time no other resource is fetched by the browser as you can see in the screenshot below. It will be more clear to you on route `/client` where the preview is blank.
2. Stylesheet and images are downloaded afterward. To see this process use the [snapshotting feature](https://developers.google.com/web/tools/chrome-devtools/network/reference#screenshots).  
<img width="850" alt="explanation-css-img" src="https://user-images.githubusercontent.com/20735862/79726893-219b6d80-8309-11ea-98f4-a358ff0b5710.png">
