### ISSUE TITLE
Server-side rendered state should be sanitized

### ISSUE THREAD

**Issue by joshuanario** [Rohitkrops/ssr#16]
https://github.com/Rohitkrops/ssr/blob/dcc76aa7f0fd6ce9b46dd7ee5c32811b2dec9080/src/template.js#L6

Consider putting a comment here that explains the security ramifications of this line of code.  The app currently does not have user input elements, but for anybody who might stumble upon this codebase (and your wonderful documentation on ssr, https://www.freecodecamp.org/news/server-side-rendering-your-react-app-in-three-simple-steps-7a82b95db82e/), there should be a raised awareness about how `JSON.stringify` of user-input data will open a vulnerability to a malicious code injection.  Please read "Pitfall 1: Server-Side Rendering Attacker-Controlled Initial State".  https://medium.com/swlh/3-security-pitfalls-every-react-developer-should-know-c04715b876b5

**Comment by RibbtDev** [comment]
Thank you for showing interest and raising this issue. There are two things you should know:
1. The initialState here is the data from your servers. The data saved would be pre-processed (this includes security actions). 
2. On client side, React has built-in Cross site scripting attack prevention mechanism. All user generated content is string.
