### ISSUE TITLE
error in path

### ISSUE THREAD

**Issue by PerspectivesLab** [Rohitkrops/ssr#4]
the demo is looking for './views/template' but doesnt exist, while doing 'npm run start'

**Comment by 2hands10fingers** [comment]
@PerspectivesLab Did you figure out the answer? I'm running into this issue as well.

**Comment by PerspectivesLab** [comment]
nope i didnt, sorry

**Comment by 2hands10fingers** [comment]
@PerspectivesLab I got an answer. You need to setup the repo in this order

npm install
npm run build
npm run start
